[project]
name = "computervision"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "imutils>=0.5.4",
    "mediapipe>=0.10.21",
    "requests>=2.32.5",
]
